### ISSUE TITLE
Cloning a database returns "output" relation, if installed

### ISSUE THREAD

**Issue by tomasrelai** [RelationalAI/rai-sdk-python#12]
I was expecting the json response from a `create_database` cloning operation to be some status report, but instead it seems to be the `output` relation, if is for some reason defined in the DB.

```python
from railib import api, config
import json

cfg = config.read()
ctx = api.Context(**cfg)
rsp = api.create_database(ctx, "clonetest", "MYENGINE", overwrite=False, source="test")
print(json.dumps(rsp, indent=2))
```

**Comment by bradlo** [comment]
The SDK simply returns what is returned by the REST API.

**Comment by bradlo** [comment]
This should be opened against raicode  if we want to change the behavior, the SDK has no control over th is.
