### ISSUE TITLE
URL path segment not properly encoded when using signature authentication

### ISSUE THREAD

**Issue by geokollias** [RelationalAI/rai-sdk-python#15]
Request signing follows the [AWS v4 spec](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html). According to it:

> The canonical URI is the URI-encoded version of the absolute path component of the URI, which is everything in the URI from the HTTP host to the question mark character ("?") that begins the query string parameters (if any).
> 
> Normalize URI paths according to RFC 3986. Remove redundant and relative path components. Each path segment must be URI-encoded twice (...)

As an example, `/documents and settings` should be encoded to `/documents%2520and%2520settings`. Similarly, `/users/auth0|60e58bb864244200711c30ae` should be encoded to `/users/auth0%257C60e58bb864244200711c30ae`.

Currently, no such encoding takes place.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-3804](https://relationalai.atlassian.net/browse/RAI-3804).

_This link is only accessible to employees of RelationalAI._
