### ISSUE TITLE
Enable config.read to read from a string

### ISSUE THREAD

**Issue by bradlo** [RelationalAI/rai-sdk-python#45]
Feature request to simplify usage from a jupyter notebook.

**Comment by bradlo** [comment]
This use case was better supported by creating the Context w/o using config.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-4079](https://relationalai.atlassian.net/browse/RAI-4079).

_This link is only accessible to employees of RelationalAI._
