### ISSUE TITLE
Example `create_database.py` broken

### ISSUE THREAD

**Issue by Ally-R** [RelationalAI/rai-sdk-python#88]
In `rai-sdk-python/examples`
```
$ python3 ./create_database.py example-db-name
Traceback (most recent call last):
  File "./create_database.py", line 37, in <module>
    run(args.database, args.profile)
  File "./create_database.py", line 26, in run
    rsp = api.create_database(ctx, database)
TypeError: create_database() missing 1 required positional argument: 'engine'
```

**Comment by Ally-R** [comment]
Hmm, I'm not sure what's going on. I pulled from main and it is up-to-date. I also ran `pip3 install rai-sdk` to make sure that's up-to-date (unless there is another method to update?). I am still getting the same error.
<img width="601" alt="rai-sdk-python create-database issue" src="https://user-images.githubusercontent.com/47114378/177601084-38313ebe-c58e-4b2c-a630-29e477834fdd.png">

**Comment by Ally-R** [comment]
I see that in the code `create_database` should not require a third input https://github.com/RelationalAI/rai-sdk-python/blob/783caed5694700c1cbd861c0329a44cb0cf36542/railib/api.py#L514

So it must be an issue with my setup... just not sure how to fix it

**Comment by Ally-R** [comment]
Upon further investigation, it seems that `create_database` is indeed correct, and the issue is that the SDK version with `pip` is not updated. This is a known issue. See https://relationalai.slack.com/archives/C02C9AV2LL9/p1657196305040269

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5859](https://relationalai.atlassian.net/browse/RAI-5859).

_This link is only accessible to employees of RelationalAI._
