### ISSUE TITLE
Return the same structure for exec and exec_async, to be compatible with other SDKs

### ISSUE THREAD

**Issue by salamehsameera** [RelationalAI/rai-sdk-python#89]
Reference: https://github.com/RelationalAI/rai-sdk-python/pull/78/#discussion_r920394344

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5989](https://relationalai.atlassian.net/browse/RAI-5989).

_This link is only accessible to employees of RelationalAI._
