### ISSUE TITLE
Improve handling of string constants

### ISSUE THREAD

**Issue by tomasrelai** [RelationalAI/rai-sdk-python#9]
If I use a bogus size string in, say, `create_compute`, the error comes back as an HTTP error.

We should consider having an enumerated type for those strings, or perhaps validating them before sending out the request? It would also be nice to list the allowable strings (or types) in the docstring.

On the other hand, if the cloud environment, say, adds more sizes, if those are built into the library, then a new release of the library would be needed to support the new sizes. Wondering if there could be a separate API call that lists the valid sizes, then --- called once when the library is initialized / before the first request is made, perhaps.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-3716](https://relationalai.atlassian.net/browse/RAI-3716).

_This link is only accessible to employees of RelationalAI._
