### ISSUE TITLE
pass through inputs from `exec` to `exec_async`

### ISSUE THREAD

**Issue by vilterp** [RelationalAI/rai-sdk-python#93]
Currently `exec` takes an `inputs` parameter but doesn't pass it through to `exec_async`, so I think the inputs get dropped: https://github.com/RelationalAI/rai-sdk-python/blob/87467fc312c08a84811f71c8a693a4bc668c26c9/railib/api.py#L685

We should add a test for this as well. A shared test suite across all the SDKs would be great; still not sure exactly how to put that together…

**Comment by NRHelmi** [comment]
Fixed in this [commit](https://github.com/RelationalAI/rai-sdk-python/commit/51bb3203c37e96a64a68ba476ed9a6df2f3a2584)
Usage `def output = foo`
```
inputs = {'foo': 'bar'}
api.exec_async(ctx, database, engine, command, inputs=inputs, readonly=readonly)
```

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6059](https://relationalai.atlassian.net/browse/RAI-6059).

_This link is only accessible to employees of RelationalAI._
